{% set name = "smesh" %}
{% set version = "9.9.0.0" %}
{% set sha256 = "bd5bddd509e5120bdd56178c37471984062e8abd36465389d64fb6e1b811a1d4" %}

package:
    name: {{ name }}
    version: {{ version }}

# source:
    # fn: {{ name }}_{{ version }}.tar.gz
    # url: https://github.com/LaughlinResearch/SMESH/archive/v{{ version }}.tar.gz
    # sha256: {{ sha256 }}
    # patches:
    #     - osx-vtk.patch  # [osx]
    #     - linker.patch  # [win]

build:
  number: 10

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]
    - ninja
    - cmake
    - git
    - python-patch
    - python =3.9
  host:
    - vtk
    - libboost-devel
    - occt =7.6.3
    - zlib
    - pthreads-win32  # [win]
    # - libmed
  run:
    - vtk
    - {{ pin_compatible('occt', max_pin='x.x.x') }}
    - zlib
    - pthreads-win32  # [win]
    # - libmed
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  source_files:
    - SMESH/test
  requires:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}   # [linux]
    - {{ cdt('libxi-devel') }}        # [linux]
    - {{ cdt('mesa-libegl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}   # [linux]
    - {{ cdt('libselinux') }}         # [linux]
    - {{ cdt('libxdamage') }}         # [linux]
    - {{ cdt('libxfixes') }}          # [linux]
    - {{ cdt('libxxf86vm') }}         # [linux]
    - cmake
    - ninja
    - catch2 < 3.0
    - libboost-devel

about:
  home: https://github.com/LaughlinResearch/SMESH
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file:  SMESH/LICENSE.txt
  summary: A complete MESH framework based on the OCCT library.
  description: Standalone version of the meshing library from the Salome Platform.

extra:
  recipe-maintainers:
    - adrianinsaval
    - looooo
