{% set name = "smesh" %}
{% set version = "8.3.0.2" %}
{% set sha256 = "ed8b64c84ab87feeb0b1fa61b616dde7c0138351447b06f977c2e0151f802552" %}
{% set commit = "8567fd0734d138ce8529c080ae85474e7a9c3c89" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}_{{ version }}.tar.gz
    # url: https://github.com/LaughlinResearch/SMESH/archive/v{{ version }}.tar.gz
    url: https://github.com/LaughlinResearch/SMESH/archive/{{ commit }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 2
    skip: True  # [py < 36]

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - ninja
    host:
        - cmake
        - vtk
        - boost-cpp
        - occt
        - netgen
        - pthread-stubs  # [unix]
        - pthreads-win32  # [win]
        - python
        - tbb-devel
        # - libmed
    run:
        - vtk
        - boost-cpp
        - occt
        - netgen
        - pthread-stubs  # [unix]
        - pthreads-win32  # [win]
        # - libmed

test:
    requires:
        - cmake
        - ninja
    files:
        - CMakeLists.txt
    commands:
        - cmake -G "Ninja" .

about:
    home: https://github.com/LaughlinResearch/SMESH
    license: LGPL2.1
    license_family: LGPL
    license_file:  LICENSE.txt
    summary: A complete MESH framework based on the OCCT library.
    description: Standalone version of the meshing library from the Salome Platform.

extra:
    recipe-maintainers:
        - looooo
