{% set name = "smesh" %}
{% set version = "8.3.0b0" %}
{% set sha256 = "008e359eb45bd77111570c4ae042d01a462d2e8e06686c3995b4e76aace066a1" %}
{% set commit = "b0df1918fc6814c093ef888deb8e155396ed359c" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}_{{ version }}.tar.gz
    url: https://github.com/LaughlinResearch/SMESH/archive/{{ commit }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - occt_version.patch

build:
    number: 8
    skip: true  # [py<35 or win32]

requirements:
    build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
    host:
        - vtk
        - boost-cpp
        - occt 7.3
        - netgen
        - pthread-stubs  # [unix]
        - pthreads-win32  # [win]
        - python
        # - libmed
    run:
        - {{ pin_compatible("vtk", max_pin="x.x.x") }}
        - {{ pin_compatible("boost-cpp", max_pin="x.x") }}
        - {{ pin_compatible("occt", max_pin="x.x") }}
        - netgen
        - pthread-stubs  # [unix]
        - pthreads-win32  # [win]
        - python
        # - libmed

test:
    requires:
        - cmake
        - ninja
    files:
        - CMakeLists.txt
    commands:
        - cmake -G "Ninja" .

about:
    home: https://github.com/LaughlinResearch/SMESH
    license: LGPL2.1
    license_family: LGPL
    license_file:  LICENSE.txt
    summary: A complete MESH framework based on the OCCT library.
    description: Standalone version of the meshing library from the Salome Platform.

extra:
    recipe-maintainers:
        - looooo
