{% set name = "smesh" %}
{% set version = "8.3.0.3" %}
{% set sha256 = "bd5bddd509e5120bdd56178c37471984062e8abd36465389d64fb6e1b811a1d4" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}_{{ version }}.tar.gz
    url: https://github.com/LaughlinResearch/SMESH/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - osx-vtk.patch  # [osx]

build:
    number: 8
    skip: True  # [py < 36]

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('libxi-devel') }}  # [linux]
        - ninja
        - cmake
    host:
        - vtk
        - boost-cpp
        - occt
        - netgen
        - pthread-stubs  # [unix]
        - pthreads-win32  # [win]
        - python
        - tbb-devel
        - zlib
        # - libmed
    run:
        - vtk
        - boost-cpp
        - occt
        - netgen
        - pthread-stubs  # [unix]
        - pthreads-win32  # [win]
        - python
        - zlib
        # - libmed

test:
    requires:
        - cmake
        - ninja
    files:
        - CMakeLists.txt
    commands:
        - cmake -G "Ninja" .

about:
    home: https://github.com/LaughlinResearch/SMESH
    license: LGPL2.1
    license_family: LGPL
    license_file:  LICENSE.txt
    summary: A complete MESH framework based on the OCCT library.
    description: Standalone version of the meshing library from the Salome Platform.

extra:
    recipe-maintainers:
        - looooo
