travis:
  secure:
    BINSTAR_TOKEN: hB7EwnaFsGQUldg5zPTqsqklLRUOvuXw80AS2T14aSfAXBT2vwuKHNrJIZRx4VL2QKah/CBZqdFcFgco85VIhUK04R5iRQU+Rdj5dFNhH2IXJdIfaCosuv832/kjhFzpD88US6a/P7wtyoHS8pjD44n0ClJbhFodNIimvJpW+VjblnQZWBVmTf/2FkcioL/CxlfaP1Tih0LtdMX37j98g9+mLcZshPIlOOWcfFAnINuFKQMR0JwYfQGU8eAxhUqzB+1wfcIR7t6DN7iY+6Qt/50gE8gEBNeuIx2TyaGBXwH0u49PZVyDZCdUj+l01H91Aq07N4EbhU+InrPI6xg3kEq8/fmtKeQTyl7KMcpAQrfq8SBrEjtftpo0ow0nLPRRLNwpUoq8o+8LYh0WPgxHn6I/3fzNFYI6CchxcM3DBykbWbdmiWGr0mkx7sZ8P85xvsVeUUeR2YCCQltsyum0wXzeJyhlKLYPnUaTadCvciWGEtyHGtPevZo8N0xeRM9vlxfNHoi25QhYMUkhLDWvv9rpi8M949M3j6h5rU3qiRSoU+/8PMh0ZWM8OS+dRBHJoiXMyzURA7tYc/LxgqIh5OdbIH5Nw3765fZX8HqonHxrTelRyI4rtVNwuBUpD2hDB+11HuFs3LYZjALe6dygBgvJNdKcCPrXk89T568/YAw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
provider:
    osx: circle